import os

from utils.fs import FileSystem

"""
This class implements a wrapper to create a writable file.
"""


class File(object):
    def __init__(self, path, name):
        # Get an instance of the FileSystem class
        self._fs = FileSystem.get_instance()
        self._file_name = self._fs.join(path, name)
        # The actual file created by open() function
        self._file = open(self._file_name, 'w')

    '''
    Return the file generated by the open() function
    '''

    def get_file(self):
        return self._file

    '''
    Return the path of the file.
    '''

    def get_path(self):
        return self._file_name

    '''
    Append text to the file
    '''

    def write(self, text):
        self._file.write(text)

    '''
    Save the file on the disk.
    '''

    def save(self):
        self._file.flush()
        os.fsync(self._file.fileno())
        self._file.close()
